//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaoTang.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhan_Vien
    {
        public long idNhanVien { get; set; }
        public string ho_ten { get; set; }
        public string gioi_tinh { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public Nullable<decimal> luong { get; set; }
        public Nullable<bool> isTrangThai { get; set; }
    }
}
