//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaoTang.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongBan
    {
        public long IdPhongBan { get; set; }
        public string tenPhongBan { get; set; }
        public Nullable<long> SoluongNhanvien { get; set; }
        public Nullable<System.DateTime> ngayTaoPhong { get; set; }
    }
}
